### ISSUE TITLE
Build navigation

### ISSUE THREAD

**Issue by Stef-ko** [steffenkleinle/my-watchlist#2]

**Comment by Ohior** [comment]
Hi, I Saw your issue and I will like to fix your "Build navigation #2". That is link the fragment navigation and add update your git ignore.
Your Readme does not explain in details what you want to achieve with the app so I won't be doing much.
Do you want me to work on it?

**Comment by steffenkleinle** [comment]
Hey @Ohior, thank you so much for the offer, we really appreciate it! Sadly this is a university project and we are not allowed to get help from other people but instead have to do it on our own :/ Sorry! We hope that works for you and best of luck! :heart:

**Comment by Ohior** [comment]
Okay, no problem
